services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SERVICE_NAME=${DB_SERVICE_NAME}
      - SOAP_URL=${SOAP_URL}
    volumes:
      - .:/app
      - ./logs:/app/logs

